server:
  port: 18090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/roma
    username: roma
    password: 1111
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    parameters:
      searchPath: classpath:/db/changelog
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
