spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/roma
    username: roma
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: test

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 18090
